tox.ini
Kombu 4.2.0 was released which is incompatible with Celery < 4.1.1. This gets the build passing again with Celery 4.0.x.
=> Ensure Kombu 4.2.0 is not used with Celery 4.0.x.

CHANGELOG.rst, celery_batches/__init__.py, t/integration/test_batches.py
This implements more of the `celery.app.trace.trace_task` (which is built from `build_tracer`). The additions allow `current_task` to be accessed properly for a `Batches` task. See https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L334-L483 for the standard Celery version.
=> Properly set the currently running task.

CHANGELOG.rst, celery_batches/__init__.py, t/integration/test_batches.py
This calls the celery success signal after the task has run. This uses the result of the celery batches call, which isn't really used anywhere else (it isn't returned to any `AsyncResult` since no particular result exists for this task run).
This also re-arranges some of the try-excepts to ensure that the post-run signal runs even if an exception happens in the success signal.
=> Call the success signal.

celery_batches/__init__.py
Avoid using celery.contrib.batches module in examples.
=> Adjust example to use celery_batches

celery_batches/__init__.py, t/integration/test_batches.py
Prior to this change, eager running of batches caused errors whereby
the batched task was passed the args and kwargs directly, rather than
wrapping them as a request, when the following was called:
`.apply_async(args, kwargs, *_args, **_kwargs)`
This change updates the minumum viable version of celery, and overrides
the new `Task.apply()` method to pass the request wrapped in a
`SimpleRequest` and a `list` to the underlying function when in eager mode.
=> Override `Task.apply()` to support eager running of Batches

CHANGELOG.rst, celery_batches/__init__.py, t/integration/tasks.py, t/integration/test_batches.py
This has a few minor changes from #16, partially taken from 80609f8917e95f0e88c4d0de4f313148b27bb96c.
* Update the docstring.
* Refine the tests a bit.
* Add back support for Python 2.
=> Minor clean-ups to eager code path (PR #16)

.travis.yml, CHANGELOG.rst, tox.ini
Adds Python 3.7/3.8 to the support matrix. Removes 3.4.
Adds Celery 4.3 and 4.4 to the support matrix.
=> Bump Python and Celery versions for tox/Travis.

.github/workflows/main.yml, setup.py, tox.ini
Celery 5.1 beta 2 is out, so we should check against this.
=> Mark as compatible with Celery 5.1.

celery_batches/__init__.py, t/integration/tasks.py
This fixes an error on Celery 5.1.0 and storing results (when passing the `request` object):
```
AttributeError: 'SimpleRequest' object has no attribute 'ignore_result'
```
This adds compatibility with celery/celery#6713.
=> Fix an issue with Celery 5.1.0 and storing results.

CHANGELOG.rst, celery_batches/__init__.py, t/integration/tasks.py, t/integration/test_batches.py
=> Do not error if passing multiple args or kwargs to the batch task.

.gitignore
`.*env*` catches `.env`, `.env3`, `.venv`, `.venv3`, `.venv310`, etc
=> `.gitignore`: Ignore virtualenvs

README.rst
=> README: Add pypi badge

CHANGELOG.rst
For developers, this separates stuff more important to them up front
=> docs(CHANGELOG): Split changes by type

.github/workflows/main.yml, t/integration/conftest.py, t/integration/test_batches.py, tox.ini
* Configures pytest / tox / GitHub Actions to run against a live RabbitMQ or Redis broker for tests.
* Skips 1 test which is failing against live brokers.
=> Run tests against live brokers (RabbitMQ & Redis)

CHANGELOG.rst, t/integration/tasks.py, t/integration/test_batches.py
This shaves a few seconds off of each test run, which isn't huge but is an easy win.
=> Reduce the flush interval in tests.

CHANGELOG.rst, celery_batches/__init__.py, requirements/test.txt, t/integration/test_batches.py, tox.ini
The goal of this was mostly to test acking so the code could be simpified to be compatible with #62, but it morphed a little bit to add a new feature:
* Properly supports overriding the `Request` used for `Batches` tasks.
* Add tests for acking.
* Simplifies the code to avoid making useless lists (for #62). (It is included here since it is a larger change than just adding type hints.)
=> Support custom `Request` classes

CHANGELOG.rst, celery_batches/__init__.py
Ports celery/celery#4358.
This would likely be difficult to come across now since protocol 2 messages have been the default for a while, but it reduces the diff of the strategy between batches & the default strategy.
=> Support "hybrid" protocol 1 & 2 messages.

CHANGELOG.rst, celery_batches/__init__.py
This gives you access to the headers in the original request, which is helpful for extracting custom headers.
=> Include `request_dict` in `SimpleRequest`

CHANGELOG.rst, README.rst, setup.cfg, tox.ini
Celery 4.4 was released in December 2019 and hasn't seen updates since July 2020. It was replaced with Celery 5.0 in Sept 2020.
The code should still work OK, but Celery 4.4 is no longer supported upstream and this reduces our testing matrix. Use celery-batches 0.7 if you still need to support Celery 4.4.
=> Drop support for Celery 4.4.

CHANGELOG.rst, celery_batches/__init__.py, t/integration/test_batches.py
Adds support for the [`task_received`](https://docs.celeryq.dev/en/v5.2.7/userguide/signals.html#task-received) signal from Celery.
This overlaps partially with #34, #81, #82.
=> Call the task_received signal.

requirements/test.txt
=> Limit pytest-celery version to 0.0.0

CHANGELOG.rst, docs/how_it_works.rst, docs/index.rst, tox.ini
=> Add "how it works" documentation

CHANGELOG.rst, celery_batches/__init__.py, t/integration/test_batches.py
In current implementation, when flush is caused by time interval, the counter does not reset, so if i set flush_every=2 and schedule 1 task and then it is processed after time interval, scheduling next task immediately after causes processing to trigger. It would make more logical sense to trigger only after 2 message occur again.
=> Reset counter after processing requests

.github/workflows/main.yml, CHANGELOG.rst, README.rst, setup.cfg, tox.ini
=> Support Celery 5.5 & Python 3.13; drop support for Python 3.8
